# -*- coding: utf-8 -*-
"""Yet another copy of Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wlEJtpafwcGAdorewAzXbma4s4UZ8I18
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df=pd.read_excel("/content/Walmart Sales.xlsx")
city_branch_performance = df.groupby(['City', 'Branch']).agg({'Quantity': 'sum', 'Unit price': 'sum'}).reset_index()
print("Performance of sales and revenue at the city and branch level:")
print(city_branch_performance)

city_branch_performance.plot(kind='bar')

average_price = df.groupby(['City', 'Branch']).agg({'Unit price': 'mean'}).reset_index()
average_price.rename(columns={'Unit price': 'Average Price'}, inplace=True)
print("\nAverage price of an item sold at each branch of the city:")
print(average_price)

average_price.plot(kind='bar')

df['Date'] = pd.to_datetime(df['Date'])
df['Month'] = df['Date'].dt.month

df['Sales'] = df['Unit price'] * df['Quantity']
df['Revenue'] = df['Sales'] * (df['Rating'] / 10)  # Assuming Rating is out of 10

grouped = df.groupby(['Product line', 'Gender', 'Payment', 'Month']).agg({
    'Sales': 'sum',
    'Revenue': 'sum'
}).reset_index()

print(grouped)